FROM node:12-alpine

RUN npm install -g yarn
RUN mkdir -p /usr/tnb-docker
WORKDIR /usr/tnb-docker
COPY package.json tsconfig.json wait.sh ./
COPY src ./src
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
RUN yarn

EXPOSE 4000
CMD /wait && yarn build && yarn start
